## Pytorch And Deep Learning Fundamentals

Deep Learning aslında Makine Öğrenmesinin bir alt kümesi. Makine öğrenmesi dataları(images, text, tables..) sayılara çevirerek aralarındaki patternleri bulmamızı sağlar. Kodlama ve Matematikle bu patternleri bulacağız.

<img src="mlvsdl.png" width="200" height="200">

<img src="tpvsml.png" width="800" height="800">
not: Eğer simple rule-based system Makine Öğrenmesine ihtiyacı yoksa KULLANMA!

#### Deep Learning Hangi durumlarda kullanılır?
* Eğer elindeki problem fazla sayıda kurala sahipse.(Geleneksel programlama fail ettiğinde ML Yardımcı olabilir.)
* Ortam ve problem sürekli değişiyorsa. Deep Learning yeni senaryoları öğrenebilir.
* Çok büyük miktardaki veriden öngörüler elde etmek istediğinde. 

#### Machine Learning vs Deep Learning
* Durumlar sürekli değişiyor o nedenle genelleme yaparak bakacağız duruma. Birbirinin yerine de kullanılabir.
* Makine Öğrenmesi genelde structured data da kullanılır. Deep Learning Unstructured data da kullanılır genelde.
<img src="mlvsdl2.png" width="800" height="800">

<img src="neuralnetworks.png" width="800" height="800">

<img src="nnanatomy.png" width="900" height="900">

<img src="typesoflearning.png" width="800" height="100">

* Supervised Learning de elinde labellenmiş birçok data olur. Bu datayı alır ML algoritmana koyarsın
* Unsupervised Learning  de elinde sadece data var. Label lar yok. Kedi ve Köperk fotoları var ama hangisi kedi hangisi köpek etiketlenmemiş. Bu durumda Kedi ve köpek resimleri arasındaki temel patternleri yakalamaya çalışırım. Sonuçta şöyle bir pattern var ise kedi değilse köpek derim. 

* Transfer Learning de , bir görev için geliştirilen bir modelin ikinci bir görevdeki bir model için başlangıç noktası olarak yeniden kullanıldığı bir makine öğrenimi yöntemidir.
* Reinforcement Learnig: Ödül ceza sistemi şeklinde olan bir öğrenme biçimi. 
<img src="reionforcement.png" width="200" height="200">

##### PYTORCH NEDİR?
* En popüler Deep Learning Platformu
* GPU veya GPU'lar üzerinde de çalışabilen Python kodları yaz Deep Learning için
* Önceden eğitilmiş Deep Learning Modellerine erişim sağlar(TorchHub)
* Veri preprocess, Data model, Deploy hepsini yapabilirsin

#### https://paperswithcode.com : Deep Learning Paperları!!!
<img src="trends.png" width="800" height="100">

* Tesla autopilot ta computer vision için Pytorch kullanıyor!
* OpenAi Pytorch üzerinden kuruldu!
* Tarım için kullanılan modeller Pytorch kullanıyor.
* MetaAı pytorch kullanıyır(Facebook)

* Gpu aslında Video Games ler için tasarlandı. Grafikleri render etmek için memory de birçok hesap yapmak gerekiyor.Pytorch Cuda yı kullanarak ML Kodunu GPU üzerinde çalıştırabiliyor.
###### Tensor Nedir?
<img src="tensors.png" width="400" height="100">
* Bir tensör, numpy dizilerine çok benzeyen genel bir n boyutlu dizidir. Genel olarak pytorch tensörlerini kullanmanın güzel yanı, bunları kolayca gpu'ya koyabilmenizdir (yalnızca işlemcide bulunan numpy dizilerinin aksine). NumPy dizisi ve tensör arasındaki fark, tensörlerin GPU gibi hızlandırıcı bellek tarafından desteklenmesidir.

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
device = torch.device("mps")

print(torch.__version__)

1.12.1


### INTRODUCTION TO TENSORS
<img src="vectorstensors.png" width="800" height="100">

In [2]:
# Pytorch tensorları torch.Tensor() kullanılarak oluşturulur!
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [3]:
scalar.ndim
# Dimension yok sadece 1 rakam

0

In [4]:
# Tensor u geri python int olarak al
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
matrix = torch.tensor([[7, 8],
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                       [3, 6 , 9],
                       [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

<img src="tensordimensions.png" width="800" height="100">

Durumu özetlersek;
<img src="summary_dims.png" width="800" height="100">

#### Random Tensors
* Bizim için çok önemli. Sinir ağları öğrenmeye başlarken başlangıçta tamamen random sayılar olan tensorler ile başlarlar. Sonra bu sayılar datayı daha iyi represent edecek şekilde ayarlanır!
* Start with random numbers --> look at data --> update random numbers --> Look at data --> update random numbers..

In [15]:
# Create random tensors of size(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1332, 0.3863, 0.2833, 0.5666],
        [0.3280, 0.2615, 0.0836, 0.7456],
        [0.0298, 0.8802, 0.3908, 0.4790]])

In [16]:
random_tensor.ndim

2

In [17]:
random_tensor = torch.rand(1, 5, 5) # random_tensor.shape = (1, 5, 5)
random_tensor

tensor([[[0.5897, 0.3498, 0.8080, 0.0247, 0.8595],
         [0.7992, 0.2662, 0.0371, 0.6280, 0.3200],
         [0.0037, 0.8762, 0.6974, 0.4823, 0.8985],
         [0.4545, 0.2973, 0.5973, 0.9077, 0.5949],
         [0.7485, 0.9755, 0.3125, 0.6893, 0.2912]]])

In [18]:
random_tensor.ndim

3

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (Red, Green, Blue)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

<img src="imagetensor.png" width="800" height="100">

In [20]:
# Zeros and Ones 
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor # Dimension error. Aynı boyutta olsalar 0 basacaktı her yere

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 2

In [ ]:
ones = torch.ones(size=(3, 4))
ones

In [ ]:
ones.dtype # Check default datatype

In [ ]:
# Creating a range of tensors and tensors-like
# Use torch.range()
import warnings
warnings.filterwarnings('ignore')

one_to_ten = torch.range(0, 10)
one_to_ten

In [22]:
torch.range(start=0, end=1000, step=77)

/var/folders/t5/7t8715tx0hl6vftpzx35308c0000gn/T/ipykernel_3516/1583739320.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0, end=1000, step=77)


tensor([  0.,  77., 154., 231., 308., 385., 462., 539., 616., 693., 770., 847.,
        924.])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

NameError: name 'one_to_ten' is not defined

### Tensor Dataypes

In [24]:
float_32_tensor  = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype # None yapmama rağmen default olarak bu gelir Pytorch un default veri tipi

torch.float32

In [26]:
float_32_tensor  = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [27]:
float_32_tensor  = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [28]:
# float32 32 bitlik bir sayıdır - float64 64 bit kullanır.
# Bu, float64'lerin iki kat daha fazla bellek kapladığı anlamına gelir
# - ve bunlar üzerinde işlem yapmak bazı makine mimarilerinde çok daha yavaş olabilir.
# Bununla birlikte, float64'ler, sayıları 32 bitlik kayan noktalardan çok daha doğru bir şekilde temsil edebilir.

a = np.array([0.123456789121212,2,3], dtype=np.float16)
print("16bit: ", a[0])

a = np.array([0.123456789121212,2,3], dtype=np.float32)
print("32bit: ", a[0])

b = np.array([0.123456789121212121212,2,3], dtype=np.float64)
print("64bit: ", b[0])

16bit:  0.1235
32bit:  0.12345679
64bit:  0.12345678912121212


In [29]:
float_32_tensor  = torch.tensor([3.0, 6.0, 9.0], 
                                dtype=None, 
                                device=None, # 2 tensor işlem yaparken atıyorum 1 tensor Gpu da diğeri Cpu da çalışıyorsa Pytorch Hata verir! 
                                requires_grad=False) # bu tensör işlemleriyle gradyanları izleyip izlememek
# requires_grad Normalde True olmalı tabi
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
# 2 farklı datatype a sahip tensorları çarpalım bakalım ne olacak?
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating Tensors(tensors operations)
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

### Matrix Multiplication
Sinir Ağlarında ve Derin öğrenmede 2 çarpma yöntemi var
 * Element-wise Multiplication (Tüm elementleri spesifik bir sayı ile çarp)
 * Matrix Multiplication (Dot Product
 
Element Wise;
    <img src="elementwise.png" width="200" height="200">
Matrix Multiplication;
    <img src="matrixmult.png" width="200" height="200">

In [33]:
# Element wise
t = torch.tensor([1, 4, 9])
print(t , "*", t)
print(f"Equals: {t*t}]")

tensor([1, 4, 9]) * tensor([1, 4, 9])
Equals: tensor([ 1, 16, 81])]


In [34]:
# Matrix Multiplication
torch.matmul(t, t) # 1*1 + 4*4 + 9*9 = 94

tensor(98)

In [35]:
%%time
# Hadi şimdi bu işlemi elle ve matmul kullanarak yaptığımdaki time ı karşılaştıralım
value = 0
for i in range(len(t)):
    value += t[i] * t[i]
value # 3.61 ms

CPU times: user 571 µs, sys: 656 µs, total: 1.23 ms
Wall time: 1.55 ms


tensor(98)

In [36]:
%%time
torch.matmul(t, t) # Neredeyse 10 kat hızlı! Vectorize Version. For loop yorar sistemi.

CPU times: user 311 µs, sys: 97 µs, total: 408 µs
Wall time: 367 µs


tensor(98)

In [37]:
# Ayrıca @ sembolü ile de matrix çarpımı yapabilirsin!!!
t @ t # Matmul 

tensor(98)

Matrix multiplication için 2 önemli noktaya dikkat etmeliyiz.
* Innner dimension lar eşleşmeli!!!
- `(3,2) @ (3, 2) Bu çalışma`
- `(2, 3) @ (3, 2) Bu çalışır`
- `(3, 2) @ (2, 3) Çalışı`
* Result matrix outer dimension ların şekline sahip olur
- `(2,3) @ (3,2) = (2, 2`
- `3,2) @ (2,3) = (3, 3)`

http://matrixmultiplication.xyz

In [38]:
torch.matmul(torch.rand(3, 10), torch.rand(10 ,3)) # inner lar eşleşiyor 3=3   Output shape: 3, 3(Outer dimensions)

tensor([[2.1361, 3.2848, 2.6351],
        [1.8913, 2.8567, 2.6359],
        [2.6541, 3.6110, 3.2971]])

In [39]:
# Deep Learning de en fazla yapılan hatalardan biri de shape error lar. Çünkü birçok matrix i çarpma işlemi yapıyoruz
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm torch.matmul'un kısaltması aynı şey yani!

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [40]:
# Tensor shape sorununu çözelim
# Birinin shape ni transpose ile manupule edeceğim! (Verilen tensorlerin axislerini değiştirir bu işlem!)
tensor_B.T #shape  2, 3 oldu

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [41]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

##### TENSOR AGGREGATION  (MIN, MAX, MEAN, SUM OF TENSORS)

In [42]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [44]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [45]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [46]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [47]:
torch.sum(x)

tensor(450)

In [48]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# Min olanın index number ına yani position ına bakalım
x.argmin()

tensor(0)

In [50]:
x.argmax()

tensor(9)

#### Reshaping, stacking, squeezing and unsqueezing
* Reshaping: reshapes an input tensor to a defined shape
* View: Return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking: Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze: Removes all 1 dimensions from a tensor
* Unsqueeze: add a 1 dimension to our target tensor
* Permute: Return a view of the input with dimensions permuted (swapped) in a certain way

In [51]:
x = torch.arange(1, 11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [52]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 9]' is invalid for input of size 10

In [53]:
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]),
 torch.Size([10, 1]))

In [54]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [55]:
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [56]:
# Change the view
z = x.view(1, 10)
z, z.shape # Reshape aynısı oldu. View shares memory with original tensor. 

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [57]:
z[:, 0] = 5 # z yi değiştirdim otomatik olarak x de değişti!
z, x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [58]:
# Stacks tensors on top of each other
x_stacked = torch.stack([x, x, x, x]) # Vertically
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [59]:
x_stacked = torch.stack([x, x, x, x], dim=1) # Horizontaly!
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [60]:
x_reshaped, x_reshaped.shape

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [61]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [62]:
# torch.permute: rearanges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) 
# Permute the original tensor to rearange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # 2.indedekini ilk başa koydum(rgb)
print(f"Original Shape{x_original.shape}")
print(f"Permuted Shape{x_permuted.shape}")

Original Shapetorch.Size([224, 224, 3])
Permuted Shapetorch.Size([3, 224, 224])


In [63]:
# Orjinal tensordeki bir değeri indexleri kullanarak değiştirelim
x_original[0 ,0, 0] = 728218
x_original[0 ,0, 0], x_permuted[0 ,0, 0]

(tensor(728218.), tensor(728218.))

#### PyTorch tensors vs Numpy
Numpy numeric hesaplamalar için kullanılan bir Python kütüphanesi. Bu nedenle Pytorch bunla etkileşim halinde
* Numpy datasını Pytorch tensoru yapmak için  --> `torch.from_numpy(ndarray)`
* Pytorch Tensor unu Numpy array a çevirmek için --> `torch.Tensor.numpy()`

In [64]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
array.dtype

dtype('float64')

In [66]:
tensor.dtype

torch.float64

In [67]:
torch.arange(1.0, 8.0).dtype

torch.float32

#### Pytorch Reproducibility(taking random out of random)
- Kısaca Sinir Ağları Nasıl öğrenir? 
`random sayı ile başla --> tensor ops --> veriyi daha iyi ifade edecek şekilde random sayıları güncelle-->Again` 
* Fakat torch.rand() dediğimde her run da farklı değerler olur!
* random.seed (Tohum yani) ile bu sorunu çözebilirim

In [68]:
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### GPU'ya ulaşma yolları
* Google Colab bedava GPU Sağlıyor
* Kendi sistem GPU'nu kullan
* Cloud Computing kullan(GCP, AWS, AZURE vb)

In [69]:
# gpu pytorch için erişelibilir mi bakalım
torch.cuda.is_available() # Diğer işletim sistemleri için True gelmesi lazım normalde

False

In [70]:
import platform
platform.platform()


'macOS-12.5.1-arm64-arm-64bit'

In [71]:
device = torch.device("mps") # IN Mac  PyTorch uses Apple’s Metal Performance Shaders (MPS) as a backend.
# Note 1: Do not confuse Apple’s MPS (Metal Performance Shaders) with Nvidia’s MPS! (Multi-Process Service).
# Note 2: The M1-GPU support feature is supported only in MacOS Monterey (12.3+).

In [72]:
# Device CPU olan bir tensor oluşturalım. Default cpu!
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [73]:
# Gpu kullanalım 
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

In [74]:
# Eğer tensor GPU üzerinde koşuyorsa bunu Numpy array ine transform edemem!
tensor_on_gpu.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [75]:
# Bu problemi aşmak için önce cpu ya set etmeliyim
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])